### PR TITLE
Logic in selecting worst sample seems flawed

### PR DESCRIPTION
**Pull request by david-clifford**
I believe the logic for selecting the worst sample is flawed, not fatally though. If the first bin of the average histogram is the furthest from eta it doesn't makes sense to drop the first sample from the subset. I believe I have a fix and if I can figure out github pull requests I'll make one.

### CODE REVIEW

**Comment by pierreroudier** [comment]
@david-clifford Thank you so much for your contribution, David! PRs are my favourite form of feedback :) 

I have accepted your PR, and will prepare a new release. Can you confirm you are happy for me to add you as a contributor?

**Comment by david-clifford** [comment]
Thanks Pierre. I'm happy to help out, and to be listed in such good company.

**Comment by pierreroudier** [comment]
@david-clifford Excellent. If you can confirm your email address - please flick me a line at the address you'll find [here](https://github.com/pierreroudier/clhs/blob/master/DESCRIPTION).

**Review by pierreroudier — COMMENTED** [review]
One issue Ive found here is that sometimes the breaks are not unique, which makes `hist` throwing an error.

**Comment by david-clifford** [comment]
Yes I've seen this happen here as well but dismissed it as an edge case and now I wonder if it is more serious. I wasn't checking the tests with each PR before sending them through for review. Let me know the steps you take (it's been a while) and I'll be sure to check in the future. Email shared.

**Pull request merged**
